akart/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from django.conf.urls.static import static #static imported for media files and url
from django.conf import settings #import setting from main project which is akart here...

urlpatterns = [
    # configure admin
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')), #dummy admin page and its track login attempt to prevent from hacking
    path('akart-akart-secret-admin-akart/', admin.site.urls), #main admin page to keep secret
    
    # akart project view
    path('',view=views.home,name='home'), 
    path('developer-profile/',view=views.developer,name='developer'),

    # configure all apps url
    path('store/',include('store.urls')), #included store app urls
    path('cart/',include('carts.urls')), #include cart app urls
    path('user/',include('accounts.urls')),#included accounts app urls
    path('order/',include('orders.urls')),#included orders app urls

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #static to use media url

carts/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',view=views.load_cart,name='cart'), #this path is use to load the cart page
    path('add_cart/<int:product_id>/',view=views.add_to_cart,name='add_cart'), # this path is used to add_to_cart, In this product_id is require
    path('remove_cart/<int:product_id>/<int:cartItem_id>/',view=views.remove_cart,name='remove_cart'), # this path is used to reduce the quantity of product, In this product_id and cart_item id is require
    path('remove_cart_item/<int:product_id>/<int:cartItem_id>/',view=views.remove_cart_item,name='remove_cart_item'), # this path is used to delete a product, In this product_id and cart_item id is require

    # checkout
    path(route='checkout/',view=views.checkout,name='checkout')
]

store/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',view=views.store,name='store'), #render store page with all available product
    path('sumbit-review/<int:product_id>/',view=views.sumbit_review,name='sumbit_review'),#sumbit the review
    path('category/<slug:category_slug>/',view=views.store,name='product_by_category'), #render store page with all product within selected category.
    path('category/<slug:category_slug>/<slug:product_slug>/',view=views.product_details,name='product_details'), #render project_details with selected product
    path(route='search/',view=views.serach_product,name='serach_product'), #render store page with all found products with keyword such in category and product
]

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg,Count

class Product(models.Model):
    
    product_name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(max_length=1000,blank=True)
    price=models.IntegerField()
    product_image=models.ImageField(upload_to='photos/product',blank=True)
    stock=models.IntegerField()
    is_available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    modified_date=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name
    
    # avaerage rating for product
    def average_rating(self):
        review=RatingReview.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg=0
        if review['average'] is not None:
            avg=float(review['average'])
        return avg
    # count of rating for product
    def count_of_ratings(self):
        review=RatingReview.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        count=0
        if review['count'] is not None:
            count=int(review['count'])
        return count

    def get_url(self):
        return reverse(viewname='product_details',args=[self.category.slug,self.slug])

# varition class has to define to change the category and value for different parameters 
class VaraitionManager(models.Manager):
    def colors(self):
        return super(VaraitionManager,self).filter(variation_category='color',is_active=True)
    def sizes(self):
        return super(VaraitionManager,self).filter(variation_category='size',is_active=True)


variation_choices=[
    ['color','color'],['size','size']
]

class Variation(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)  #by default related-name is  class name is taking
    variation_category=models.CharField(max_length=250,choices=variation_choices)
    variation_value=models.CharField(max_length=250,blank=False)
    is_active=models.BooleanField(default=True)
    created_date=models.DateTimeField(auto_now=True)

    objects=VaraitionManager()

    def __str__(self):
        return self.variation_value
    
class RatingReview(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(Account,on_delete=models.CASCADE)
    rating=models.FloatField()
    subject=models.CharField(max_length=150)
    review=models.TextField(max_length=500)
    status=models.BooleanField(default=True)
    ip=models.CharField(max_length=100,null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    

class ProductGallery(models.Model):
    product=models.ForeignKey(Product,default=None,on_delete=models.CASCADE)
    image=models.ImageField(max_length=255,upload_to='store/products')

    class Meta:
        verbose_name='Product Gallery'
        verbose_name_plural='Product Galleries'

    def __str__(self):
        return self.product.product_name

store/forms.py
from django import forms
from .models import RatingReview


class ReviewForm(forms.ModelForm):
    review=forms.CharField(required=False)
    subject=forms.CharField(required=False)
    class Meta:
        model=RatingReview
        fields=['rating','subject','review']

carts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from store.models import Product,Variation
from .models import Cart,CartItem

from django.contrib.auth.decorators import login_required

def _cart_id(request):
    # collecting session from request either existing or created new
    cart_id=request.session.session_key
    if not cart_id:
        cart_id=request.session.create()
    return cart_id

def add_to_cart(request,product_id):

    product=Product.objects.get(id=product_id) #fetching product with its id
    product_variation=[]
    if request.method=='POST':
        i=1
        for item in request.POST:
            key=item.strip()
            key_value=request.POST[key].strip()
            if 'csrf' in key:
                continue

            # collect the variations from Varition Model
            variation=Variation.objects.get(product=product,variation_category__iexact=key,variation_value__iexact=key_value,is_active=True)
            product_variation.append(variation) #append all varition to use
        
        

    if request.user.is_authenticated:
        cart_item=CartItem.objects.filter(product=product,user=request.user) #check available product with refer to cart of user
    else:
        cart,created=Cart.objects.get_or_create(cart_id=_cart_id(request=request)) #either get the cart with cart_id (i.e session key) or create with it.
        cart_item=CartItem.objects.filter(product=product,cart=cart) #check available product with refer to cart of session
    
    '''
    If product in cart _items exist then loop all cart_items to check same variations available or not? If yes then increase the quantity of product and redirect  to cart page.
    If product is not available withing cart_items then create new one and with added variations

    '''

    if cart_item.exists():
        
        for item in cart_item:
            if product_variation == list(item.variations.all()):
                item.quantity+=1
                item.save()
                return redirect ('cart')

        
    if request.user.is_authenticated:
        cart_item=CartItem.objects.create(product=product,user=request.user,quantity=1)
    else:
        cart_item=CartItem.objects.create(product=product,cart=cart,quantity=1)
    if len(product_variation)>0:
        cart_item.variations.clear()
        for item in product_variation:
            cart_item.variations.add(item)
    cart_item.save()
    return redirect ('cart')
     

def remove_cart(request,product_id,cartItem_id):

    # collect cart from session id..
    # collect product from product which is from param 'product_id'
    # collect cart_item from cart_item_id from param 'cartItem_id'
    
    if request.user.is_authenticated:
        product=get_object_or_404(Product,id=product_id)
        cart_item=CartItem.objects.get(id=cartItem_id,user=request.user,product=product)
    else:
        cart=Cart.objects.get(cart_id=_cart_id(request=request))
        product=get_object_or_404(Product,id=product_id)
        cart_item=CartItem.objects.get(id=cartItem_id,cart=cart,product=product)

    # if quantity is more than 1 then reduce the quantity else delete it
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart')

def remove_cart_item(request,product_id,cartItem_id):

    # collect cart from session id..
    # collect product from product which is from param 'product_id'
    # collect cart_item from cart_item_id from param 'cartItem_id'
    if request.user.is_authenticated:
        product=get_object_or_404(Product,id=product_id)
        cart_item=CartItem.objects.get(id=cartItem_id,user=request.user,product=product)
    else:
        cart=Cart.objects.get(cart_id=_cart_id(request=request))
        product=get_object_or_404(Product,id=product_id)
        cart_item=CartItem.objects.get(id=cartItem_id,cart=cart,product=product)

    # delete product from cart_item
    cart_item.delete()
    return redirect('cart')


def load_cart(request,total=0,quantity=0,cart_items=None,grand_total=0,tax=0):
    
    try:
        
        if request.user.is_authenticated:
            cart_items=CartItem.objects.filter(user=request.user,is_active=True)
        else:
            cart=Cart.objects.get(cart_id=_cart_id(request=request)) # collect cart from using session
            cart_items=CartItem.objects.filter(cart=cart,is_active=True) # collect cart_items from using cart
        
        # calculate the total, tax and grand_total
        for cart_item in cart_items:
            total+=cart_item.product.price*cart_item.quantity
            quantity+=cart_item.quantity
        
        tax=(2*total)/100
        grand_total=total+tax
    except:
        pass

    # store require key and value with context to use in template
    context={
        'cart_items':cart_items,
        'total':total,
        'quantity':quantity,
        'tax':tax,
        'grand_total':grand_total


    }
    return render(request=request,template_name='store/cart.html',context=context)

@login_required(login_url='login')
def checkout(request,total=0,quantity=0,cart_items=None,grand_total=0,tax=0):
    try:
        
        if request.user.is_authenticated:
            cart_items=CartItem.objects.filter(user=request.user,is_active=True)
        else:
            cart=Cart.objects.get(cart_id=_cart_id(request=request)) # collect cart from using session
            cart_items=CartItem.objects.filter(cart=cart,is_active=True) # collect cart_items from using cart
        
        # calculate the total, tax and grand_total
        for cart_item in cart_items:
            total+=cart_item.product.price*cart_item.quantity
            quantity+=cart_item.quantity
        
        tax=(2*total)/100
        grand_total=total+tax
    except:
        pass

    # store require key and value with context to use in template
    context={
        'cart_items':cart_items,
        'total':total,
        'quantity':quantity,
        'tax':tax,
        'grand_total':grand_total


    }
    return render(request=request,template_name='store/checkout.html',context=context)

store/views.py
#render: it is used to render the template
#get_object_or_404: It help to find object from model class else redirect to error page
from django.shortcuts import render,get_object_or_404,redirect

# models import from different app based on use
from .models import Product,RatingReview,ProductGallery
from category.models import Category
from carts.models import * 
from carts.views import _cart_id 
from .forms import ReviewForm
from django.contrib import messages
from django.http import HttpResponse
from orders.models import OrderProduct
from orders.views import get_client_ip
from django.contrib.auth.decorators import login_required

# import Q to make somplex queries
from django.db.models import Q

# paginator : please use documentation of django
from django.core.paginator import PageNotAnInteger,Paginator,EmptyPage

# render products by category slug and if category slug is missing in param then render all product to the store
def store(request,category_slug=None):

    if category_slug is not None:
        categories=get_object_or_404(Category,slug=category_slug)
        products=Product.objects.filter(category=categories,is_available=True).order_by('id')

    else:
        products=Product.objects.all().filter(is_available=True).order_by('id')

    # paginator code added
    paginator=Paginator(products,27)
    page=request.GET.get('page')
    page_products=paginator.get_page(page)


    # all product counts
    product_count=products.count()
    context={
        'products':page_products,
        'product_count':product_count,

    }
    
    return render(request=request,template_name='store/store.html',context=context)


# rebder the product details html file wrt category and product slug in param
def product_details(request,category_slug,product_slug):
    try:
        single_product=Product.objects.get(category__slug=category_slug,slug=product_slug) #collect product details by using param such that 'category_slug' and 'product_slug'.
        if request.user.is_authenticated:
            cart_exits=CartItem.objects.filter(user=request.user,product=single_product).exists() #check this product is available to cart or not
        else:
            cart_exits=CartItem.objects.filter(cart__cart_id=_cart_id(request=request),product=single_product).exists() #check this product is available to cart or not
        reviews=RatingReview.objects.filter(product=single_product)
        product_gelleries=ProductGallery.objects.filter(product=single_product)
    except Exception as e:
        raise e
    context={
        'single_product':single_product,
        'cart_exits':cart_exits,
        'reviews':reviews,
        'product_gelleries':product_gelleries
    }
    return render(request=request,template_name='store/product_details.html',context=context)

def serach_product(request):
    products=None
    product_count=0
    if 'keyword' in request.GET:
        #collect the keyword and  remove the white spaces
        keyword=request.GET['keyword'] 
        keyword=keyword.strip() 

        # collect all products form Query
        products=Product.objects.order_by('modified_date').filter(Q(category__category_name__icontains=keyword) | Q(category__slug__icontains=keyword) |
         Q(slug__icontains=keyword) | Q(description__icontains=keyword) | Q(product_name__icontains=keyword) )
        product_count=products.count()
    
    context={
        'products':products,
        'product_count':product_count,

    }
    
    return render(request=request,template_name='store/store.html',context=context)

@login_required(login_url='login')
def sumbit_review(request,product_id):
    
    '''
        from forms.py if rating has done in past then update it and if its new then update with new
    '''

    url=request.META.get('HTTP_REFERER')
    if request.method=='POST':
        order_product=OrderProduct.objects.filter(user=request.user,product__id=product_id).exists()
        if not order_product:
            messages.error(request=request,message='You are not permiited to sumbit the review. To do this please purchase the product!!')
            return redirect(url)
        try:
            review=RatingReview.objects.get(user__id=request.user.id,product__id=product_id)
            form=ReviewForm(request.POST,instance=review)
            form.save()
            messages.success(request=request,message='Thank you for contributed. Your review has updated!')
            return redirect(url)
        except RatingReview.DoesNotExist:
            form=ReviewForm(request.POST)
            if form.is_valid():
                review=RatingReview()
                review.subject=form.cleaned_data['subject']
                review.review=form.cleaned_data['review']
                review.rating=form.cleaned_data['rating']
                review.ip=get_client_ip(request=request)
                review.product_id=product_id
                review.user_id=request.user.id
                review.save()
                messages.success(request=request,message='Thank you for contributed. Your review has submitted!')
                return redirect(url)
            messages.error(request=request,message='You are not permiited to sumbit the review!')
            return redirect(url)
    return redirect('home')

templates/store/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap mainImage" id="mainImage">
           <center class="product-image-container"><img src="{{single_product.product_image.url}}" class="product-image"></center>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
    <ul class="thumb">
        <li>  
            <a href="{{single_product.product_image.url}}"><img src="{{single_product.product_image.url}}" alt="Product Images"></a>
            {% for i in product_gelleries %}
            <a href="{{i.image.url}}"><img src="{{i.image.url}}" alt="Product Images"></a>
            {% endfor %}
        </li>
    </ul>
    </aside>
    <main class="col-md-6 border-left">
       
      <form action="{% url 'add_cart' single_product.id %}" method="POST">
        {% csrf_token %}
              <article class="content-body">
              
              <h2 class="title">{{single_product.product_name}}</h2>
              <p>
                <span class="user-rating">
                        
                <i class="fa fa-star{% if single_product.average_rating < 0.5 %}-o{% elif  single_product.average_rating >= 0.5 and  single_product.average_rating < 1 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.average_rating < 1.5 %}-o{% elif  single_product.average_rating >= 1.5 and  single_product.average_rating < 2 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.average_rating < 2.5 %}-o{% elif  single_product.average_rating >= 2.5 and  single_product.average_rating < 3 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.average_rating < 3.5 %}-o{% elif  single_product.average_rating >= 3.5 and  single_product.average_rating < 4 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.average_rating < 4.5 %}-o{% elif  single_product.average_rating >= 4.5 and  single_product.average_rating < 5 %}-half-o{% endif %}"></i>
                
                
                </span>
                <span>
                    ({{single_product.count_of_ratings}} Ratings & Reviews)
                </span>
            </p>
              
              <div class="mb-3"> 
                  <var class="price h4">${{single_product.price}}</var> 
              </div> 
              
              <p>{{single_product.description}}</p>
              
              
              <hr>
                    <div class="row">
                      <div class="item-option-select">
                          <h6>Choose Color</h6>
                          <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                            <select name="color" id="color" class="form-control" required>
                                <option value="" selected>Select</option>
                                {% for i in single_product.variation_set.colors %}
                                <option value="{{i.variation_value}}">{{i.variation_value | capfirst}}</option>
                                
                                {% endfor %}
                            </select>
                           
                          </div> 
                      </div>
                  </div> <!-- row.// -->
                  <div class="row">
                      <div class="item-option-select">
                          <h6>Select Size</h6>
                          
                          <select name="size" id="size" class="form-control" required>
                            <option value="" selected>Select</option>
                            {% for i in single_product.variation_set.sizes %}
                            <option value="{{i.variation_value}}">{{i.variation_value | capfirst}}</option>
                            {% endfor %}
                        </select>
                       

                          
                      </div>
                  </div> <!-- row.// -->
                  <hr>
                  {% if single_product.stock > 0 %}
                    {% if not cart_exits %}
                      <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
                    {% else %}
                      <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
                      <a href="{% url 'cart' %}" class="btn  btn-success"> <span class="text">Go to cart</span> <i class="fas fa-eye"></i>  </a>
                    {% endif %}
                      {% else %}
                      <span class="btn  btn-light disabled "> <span class="text">Out of stock</span> <i class="fas fa-shopping-cart"></i>  </span>
                  {% endif %}
                  </article> <!-- product-info-aside .// -->
                </form> <!--Form-->
          </main> <!-- col.// -->
         
        </div> <!-- row.// -->
    </div> <!-- card.// -->
   
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews</h3>  
            <p>
                <span class="user-rating">
                        
                <i class="fa fa-star{% if single_product.average_rating < 0.5 %}-o{% elif  single_product.average_rating >= 0.5 and  single_product.average_rating < 1 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.average_rating < 1.5 %}-o{% elif  single_product.average_rating >= 1.5 and  single_product.average_rating < 2 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.average_rating < 2.5 %}-o{% elif  single_product.average_rating >= 2.5 and  single_product.average_rating < 3 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.average_rating < 3.5 %}-o{% elif  single_product.average_rating >= 3.5 and  single_product.average_rating < 4 %}-half-o{% endif %}"></i>
                <i class="fa fa-star{% if single_product.average_rating < 4.5 %}-o{% elif  single_product.average_rating >= 4.5 and  single_product.average_rating < 5 %}-half-o{% endif %}"></i>
                
                
                </span>
                <span>
                    ({{single_product.count_of_ratings}} Ratings & Reviews)
                </span>
            </p>
        </header>
        {% if user.is_authenticated %}
        {% include 'includes/alerts.html' %}
        <form action="{% url 'sumbit_review' single_product.id %}" method="POST" class="form">

            {% csrf_token %}
            <label for="subject">Rate this product:</label>
            <br>
            <div id="rate" class="rate">
                
                <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
                <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" class="half" title="4.5"></label>
                <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8"  title="4"></label>
                <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" class="half" title="3.5"></label>
                <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
                <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" class="half" title="2.5"></label>
                <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4"  title="2"></label>
                <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" class="half" title="1.5"></label>
                <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
                <input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" class="half" title="0.5"></label>
                
            </div>
            <br>
           <h5>Review this product</h5>
           <input type="text" name="subject" maxlength="150" id="subject" class="form-control" placeholder="Title(optional)">
           
           <textarea name="review" maxlength="500" id="review" class="form-control" rows="4" placeholder="Description(optional)"></textarea>
           <br>
           <button type="submit" class="btn btn-primary">Sumbit</button>
           

        </form>
        <br>
        {% else %}
        <a href="{% url 'login' %}?next={{ single_product.get_url }}" >Review this product? Login.</a>
        <br><br>
        {% endif %}

        {% for review in reviews %}
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{{review.user.profile_picture_url}}" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">{{review.updated_at}}</span>  
                    <h6 class="mb-1">{{review.user.first_name | capfirst}} {{review.user.last_name | capfirst}}</h6>
                    <span class="user-rating">
                        
                        <i class="fa fa-star{% if review.rating == 0.5 %}-half-o {% elif review.rating < 1 %}-o{% endif %}"></i>
                        <i class="fa fa-star{% if review.rating == 1.5 %}-half-o {% elif review.rating < 2 %}-o{% endif %}"></i>
                        <i class="fa fa-star{% if review.rating == 2.5 %}-half-o {% elif review.rating < 3 %}-o{% endif %}"></i>
                        <i class="fa fa-star{% if review.rating == 3.5 %}-half-o {% elif review.rating < 4 %}-o{% endif %}"></i>
                        <i class="fa fa-star{% if review.rating == 4.5 %}-half-o {% elif review.rating < 5 %}-o{% endif %}"></i>
                        
                        
                    </span>
                    
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <h6 class="mb-1">{{review.subject | capfirst}}</h6>
                <p>
                    {{review.review}}
                </p>	
            </div>
        </article>
        {% endfor %}
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
  
{% endblock %}